# Stratusd configuration (exposed as environment variables under the hood)

# The password used to authenticate with the backend WebSocket API (if left
# undefined, authentication is disabled)
#STRATUSD_BACKEND_PASSWORD=hunter2

# The URL of the backend WebSocket API (REQUIRED)
STRATUSD_BACKEND_URL=wss://api.playstratus.io

# The directory containing the packaged games (defaults to "../games/build")
STRATUSD_GAME_DIR=/var/lib/stratusd/games

# The IP for stratusd that clients should connect to (defaults to 127.0.0.1)
#STRATUSD_IP=127.0.0.1

# The port to listen for WebTransport connections on (defaults to 4433)
STRATUSD_PORT=443
