# Stratusd configuration (exposed as environment variables under the hood)

# The directory containing the packaged games (defaults to "../games/build")
STRATUSD_GAME_DIR=/var/lib/stratusd/games

# The UUID (i.e. filename) of the game to launch (TEMPORARY, defaults to
# "sleep")
#STRATUSD_GAME_UUID=CHANGEME

# The H264 file to save encoded output (TEMPORARY, defaults to
# "encode_output.h264")
STRATUSD_OUTPUT_FILE=/var/lib/stratusd/output.h264
