# Stratusd configuration (exposed as environment variables under the hood)

# The URL of the backend WebSocket API (REQUIRED)
STRATUSD_BACKEND_URL=wss://api.playstratus.io

# The directory containing the packaged games (defaults to "../games/build")
STRATUSD_GAME_DIR=/var/lib/stratusd/games

# The H264 file to save encoded output (TEMPORARY, defaults to
# "encode_output.h264")
STRATUSD_OUTPUT_FILE=/var/lib/stratusd/output.h264
