name: Backend CD

on:
  push:
    branches:
      - "*"
    paths:
      - "backend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
      ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
      REFRESH_SECRET: ${{ secrets.REFRESH_SECRET }}
    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm ci

      - name: Deploy with Serverless Framework
        run: npm run deploy
